=== raviteja-bhupatiraju/Hermes2/xsd/mirror/ns.medbiq.org/curriculuminventory/v10/curriculuminventory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--edited with XMLSpy v2020 rel. 2 sp1 (x64) (http://www.altova.com) by Johmarx Patton (AAMC) 2020-09-21 -->
<!--MedBiquitous Curriculum Inventory Standard, XML Schema DRAFT v10 -->
<xsd:schema xmlns="http://ns.medbiq.org/curriculuminventory/v10/" xmlns:m="http://ns.medbiq.org/member/v1/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:co="http://ns.medbiq.org/competencyobject/v1/" xmlns:cf="http://ns.medbiq.org/competencyframework/v1/" xmlns:lom="http://ltsc.ieee.org/xsd/LOM" xmlns:hx="http://ns.medbiq.org/lom/extend/v1/" xmlns:hv="http://ns.medbiq.org/lom/vocab/v1/" xmlns:mbq="http://ns.medbiq.org/common/v2/" targetNamespace="http://ns.medbiq.org/curriculuminventory/v10/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:import namespace="http://ns.medbiq.org/member/v1/" schemaLocation="http://ns.medbiq.org/member/v1/member.xsd"/>
	<xsd:import namespace="http://ns.medbiq.org/competencyobject/v1/" schemaLocation="http://ns.medbiq.org/competencyobject/v1/competencyobject.xsd"/>
	<xsd:import namespace="http://ns.medbiq.org/lom/extend/v1/" schemaLocation="http://ns.medbiq.org/lom/healthcare/healthcaremetadata.xsd"/>
	<xsd:import namespace="http://ltsc.ieee.org/xsd/LOM" schemaLocation="http://ns.medbiq.org/lom/healthcarelom.xsd"/>
	<xsd:import namespace="http://ns.medbiq.org/competencyframework/v1/" schemaLocation="http://ns.medbiq.org/competencyframework/v1/competencyframework.xsd"/>
	<xsd:import namespace="http://ns.medbiq.org/lom/vocab/v1/" schemaLocation="http://ns.medbiq.org/lom/healthcare/healthcarevocabularies.xsd"/>
	<xsd:import namespace="http://ns.medbiq.org/common/v2/" schemaLocation="http://ns.medbiq.org/common/v2/common.xsd"/>
	<!--Copyright © 2020 AAMC/The MedBiquitous Program. All Rights Reserved. https://www.medbiq.org-->
	<!--Users are bound by the terms of the MedBiquitous Standards Public License and Terms of Use, https://www.medbiq.org/license-->
	<!--Previously Modified May 29, 2014 by Valerie Smothers (Johns Hopkins University) -->
	<!--Previously Modified July 28, 2020 by Johmarx Patton (AAMC) -->
	<!--Last Modified September 21, 2020 by Johmarx Patton (AAMC) -->
	<!--[with each subsequent modification please keep the previous modification date lines and edit "Last" to "Previously"]-->
	<xsd:simpleType name="IDDomainType">
		<xsd:restriction base="xsd:anyURI">
			<xsd:pattern value="idd:\S*:\S*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="OrderType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Ordered"/>
			<xsd:enumeration value="Unordered"/>
			<xsd:enumeration value="Parallel"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="OneToTen">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:maxInclusive value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StatusType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="successful"/>
			<xsd:enumeration value="unsucessful"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EventReferenceType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\s*/CurriculumInventory/Events/Event\[@id\s?=\s?'[^']+'\]\s*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AcademicLevelReferenceType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\s*/CurriculumInventory/AcademicLevels/Level\[@number\s?=\s?'(\d|10)'\]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SequenceBlockReferencePatternType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\s*/CurriculumInventory/Sequence/SequenceBlock\[@id\s?=\s?'[^']+'\]\s*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CompetencyObjectReferenceType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\s*/CurriculumInventory/Expectations/CompetencyObject\[lom:lom/lom:general/lom:identifier/lom:entry\s?=\s?'[^']+'\]\s*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IntegrationBlockReferenceType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\s*/CurriculumInventory/Integration/IntegrationBlock\[@id\s?=\s?'[^']+'\]\s*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EventDurationType">
		<xsd:restriction base="xsd:duration">
			<xsd:pattern value="PT\d+H\d+M|PT\d+H|PT\d+M"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="OneToOneHundred">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:maxInclusive value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ClerkshipModelType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="integrated"/>
			<xsd:enumeration value="rotation"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RequiredType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Required"/>
			<xsd:enumeration value="Optional"/>
			<xsd:enumeration value="Required In Track"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PurposeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Formative"/>
			<xsd:enumeration value="Summative"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SchedulingType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Longitudinal"/>
			<xsd:enumeration value="Flexible"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="VocabularyTermType">
		<xsd:simpleContent>
			<xsd:extension base="mbq:NonNullStringType">
				<xsd:attribute name="source"/>
				<xsd:attribute name="sourceID"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="LevelType">
		<xsd:sequence>
			<xsd:element name="Label" type="mbq:NonNullStringType"/>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="number" type="OneToTen" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="AcademicLevelsType">
		<xsd:sequence>
			<xsd:element name="LevelsInProgram" type="OneToTen"/>
			<xsd:element name="Level" type="LevelType" maxOccurs="10"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="EventsType">
		<xsd:sequence>
			<xsd:element name="Event" type="EventType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ExpectationsType">
		<xsd:sequence>
			<xsd:element name="CompetencyObject" type="co:CompetencyObjectType" maxOccurs="unbounded"/>
			<xsd:element name="CompetencyFramework" type="cf:CompetencyFrameworkType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SequenceType">
		<xsd:sequence>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:element name="SequenceBlock" type="SequenceBlockType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="DatesType">
		<xsd:sequence>
			<xsd:element name="StartDate" type="xsd:date"/>
			<xsd:element name="EndDate" type="xsd:date"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TimingType">
		<xsd:choice maxOccurs="2">
			<xsd:element name="Duration" type="xsd:duration"/>
			<xsd:element name="Dates" type="DatesType"/>
		</xsd:choice>
	</xsd:complexType>
	<xsd:complexType name="SequenceBlockType">
		<xsd:sequence>
			<xsd:element name="Title" type="mbq:NonNullStringType"/>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:element name="Timing" type="TimingType"/>
			<xsd:element name="SequenceBlockLevels" type="SequenceBlockLevelsType"/>
			<xsd:element name="ClerkshipModel" type="ClerkshipModelType" minOccurs="0"/>
			<xsd:element name="CompetencyObjectReference" type="CompetencyObjectReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Precondition" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:element name="Postcondition" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="SequenceBlockEvent" type="SequenceBlockEventType"/>
				<xsd:element name="SequenceBlockReference" type="SequenceBlockReferenceType"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="id" use="required"/>
		<xsd:attribute name="required" type="RequiredType" use="required"/>
		<xsd:attribute name="order" type="OrderType"/>
		<xsd:attribute name="minimum" type="xsd:positiveInteger"/>
		<xsd:attribute name="maximum" type="xsd:positiveInteger" use="optional"/>
		<xsd:attribute name="track" type="xsd:boolean" default="false"/>
	</xsd:complexType>
	<xsd:complexType name="SequenceBlockLevelsType">
		<xsd:sequence>
			<xsd:element name="StartingAcademicLevel" type="AcademicLevelReferenceType"/>
			<xsd:element name="EndingAcademicLevel" type="AcademicLevelReferenceType"/>
		</xsd:sequence>
		<!-- <xsd:attribute name="scheduling" type="SchedulingType"/> This line is to be included in future versions but will not be included in DRAFT v10 -->
	</xsd:complexType>
	<xsd:complexType name="SequenceBlockReferenceType">
		<xsd:simpleContent>
			<xsd:extension base="SequenceBlockReferencePatternType">
				<xsd:attribute name="order" type="xsd:positiveInteger"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="IntegrationBlockType">
		<xsd:sequence>
			<xsd:element name="Title" type="mbq:NonNullStringType"/>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:element name="CompetencyObjectReference" type="CompetencyObjectReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="EventReference" type="EventReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="SequenceBlockReference" type="SequenceBlockReferenceType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="IntegrationType">
		<xsd:sequence>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:element name="IntegrationBlock" type="IntegrationBlockType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="NonNullStringWithId">
		<xsd:simpleContent>
			<xsd:extension base="mbq:NonNullStringType">
				<xsd:attribute name="id"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="DomainID">
		<xsd:simpleContent>
			<xsd:extension base="mbq:NonNullStringType">
				<xsd:attribute name="domain" type="IDDomainType"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="ProgramType">
		<xsd:sequence>
			<xsd:element name="ProgramName" type="mbq:NonNullStringType"/>
			<xsd:element name="ProgramID" type="DomainID"/>
			<xsd:element name="EducationalContext" type="hv:contextValues" minOccurs="0"/>
			<xsd:element name="Profession" type="VocabularyTermType" minOccurs="0"/>
			<xsd:element name="Specialty" type="VocabularyTermType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SequenceBlockEventType">
		<xsd:sequence>
			<xsd:element name="EventReference" type="EventReferenceType"/>
			<xsd:element name="StartDate" type="xsd:date" minOccurs="0"/>
			<xsd:element name="EndDate" type="xsd:date" minOccurs="0"/>
		</xsd:sequence>
		<xsd:attribute name="required" type="xsd:boolean" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ObjectType">
		<xsd:choice>
			<xsd:element name="CompetencyObject" type="co:CompetencyObjectType"/>
		</xsd:choice>
		<xsd:attribute name="id" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="AssessmentMethodType">
		<xsd:simpleContent>
			<xsd:extension base="mbq:NonNullStringType">
				<xsd:attribute name="purpose" type="PurposeType" use="required"/>
				<xsd:attribute name="source"/>
				<xsd:attribute name="sourceID"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="InstructionalMethodType">
		<xsd:simpleContent>
			<xsd:extension base="mbq:NonNullStringType">
				<xsd:attribute name="primary" type="xsd:boolean" use="required"/>
				<xsd:attribute name="source"/>
				<xsd:attribute name="sourceID"/>
				<xsd:attribute name="instructionalMethodDuration" type="EventDurationType"/> <!-- This was added for DRAFT v10 -->
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="EventType">
		<xsd:sequence>
			<xsd:element name="Title" type="mbq:NonNullStringType"/>
			<xsd:element name="EventDuration" type="EventDurationType"/>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/>
			<xsd:element name="Keyword" type="lom:keyword" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="Interprofessional" type="xsd:boolean" default="false" minOccurs="0"/>
			<xsd:element name="CompetencyObjectReference" type="CompetencyObjectReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="ResourceType" type="VocabularyTermType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="InstructionalMethod" type="InstructionalMethodType"/>
				<xsd:element name="AssessmentMethod" type="AssessmentMethodType"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="id" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="CurriculumInventoryType">
		<xsd:sequence>
			<xsd:element name="ReportID" type="DomainID"/>
			<xsd:element name="Institution" type="m:InstitutionInfoType"/>
			<xsd:element name="Program" type="ProgramType"/>
			<xsd:element name="Title" type="mbq:NonNullStringType"/>
			<xsd:element name="ReportDate" type="xsd:date"/>
			<xsd:element name="ReportingStartDate" type="xsd:date"/>
			<xsd:element name="ReportingEndDate" type="xsd:date"/>
			<xsd:element name="Language" type="xsd:language"/>
			<xsd:element name="Description" type="mbq:NonNullStringType" minOccurs="0"/> <!-- This was changed to optional for DRAFT v10 -->
			<xsd:element name="SupportingLink" type="xsd:anyURI" minOccurs="0"/>
			<xsd:element name="Events" type="EventsType"/>
			<xsd:element name="Expectations" type="ExpectationsType"/>
			<xsd:element name="AcademicLevels" type="AcademicLevelsType"/>
			<xsd:element name="Sequence" type="SequenceType" minOccurs="0"/>
			<xsd:element name="Integration" type="IntegrationType" minOccurs="0"/>
			<xsd:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="CurriculumInventory" type="CurriculumInventoryType"/>
</xsd:schema>

=== raviteja-bhupatiraju/Hermes2/bundles/edu.louisiana.caai.medbiq.model/templates/curriculum-inventory-v1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Template of a new Curriculum Inventory report, version 1.0 (Hermes 2): one event, one competency
     object, one academic level and one sequence block that ties them together. Placeholders: ${title}, ${language},
     ${date}, ${dateTime}, ${id}. -->
<CurriculumInventory xmlns="http://ns.medbiq.org/curriculuminventory/v1/" xmlns:lom="http://ltsc.ieee.org/xsd/LOM"
		xmlns:a="http://ns.medbiq.org/address/v1/" xmlns:cf="http://ns.medbiq.org/competencyframework/v1/"
		xmlns:co="http://ns.medbiq.org/competencyobject/v1/" xmlns:hx="http://ns.medbiq.org/lom/extend/v1/"
		xmlns:m="http://ns.medbiq.org/member/v1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://ns.medbiq.org/curriculuminventory/v1/ http://ns.medbiq.org/curriculuminventory/v1/curriculuminventory.xsd">
	<ReportID domain="idd:example.edu:curriculuminventory">${id}</ReportID>
	<Institution>
		<m:InstitutionName>Name of the school</m:InstitutionName>
	</Institution>
	<Program>
		<ProgramName>M.D.</ProgramName>
		<ProgramID domain="idd:example.edu:program">MD</ProgramID>
	</Program>
	<Title>${title}</Title>
	<ReportDate>${date}</ReportDate>
	<ReportingStartDate>${date}</ReportingStartDate>
	<ReportingEndDate>${date}</ReportingEndDate>
	<Language>${language}</Language>
	<Description>A description of the curriculum.</Description>
	<Events>
		<Event id="E1">
			<Title>First event</Title>
			<EventDuration>PT1H</EventDuration>
			<CompetencyObjectReference>/CurriculumInventory/Expectations/CompetencyObject[lom:lom/lom:general/lom:identifier/lom:entry='urn:uuid:${id}:objective-1']</CompetencyObjectReference>
			<InstructionalMethod primary="true" source="AAMC" sourceID="IM013">Lecture</InstructionalMethod>
		</Event>
	</Events>
	<Expectations>
		<CompetencyObject>
			<lom:lom>
				<lom:general>
					<lom:identifier>
						<lom:catalog>URI</lom:catalog>
						<lom:entry>urn:uuid:${id}:objective-1</lom:entry>
					</lom:identifier>
					<lom:title>
						<lom:string language="${language}">First learning objective</lom:string>
					</lom:title>
				</lom:general>
			</lom:lom>
		</CompetencyObject>
	</Expectations>
	<AcademicLevels>
		<LevelsInProgram>1</LevelsInProgram>
		<Level number="1">
			<Label>Year 1</Label>
		</Level>
	</AcademicLevels>
	<Sequence>
		<SequenceBlock id="S1" required="Required">
			<Title>First course</Title>
			<Timing>
				<Dates>
					<StartDate>${date}</StartDate>
					<EndDate>${date}</EndDate>
				</Dates>
			</Timing>
			<Level>/CurriculumInventory/AcademicLevels/Level[@number='1']</Level>
			<SequenceBlockEvent required="true">
				<EventReference>/CurriculumInventory/Events/Event[@id='E1']</EventReference>
			</SequenceBlockEvent>
		</SequenceBlock>
	</Sequence>
</CurriculumInventory>
